import jsPDF from "jspdf";

export function generatePDFReport(interview) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210; // A4 width
  const margin = 20;
  let y = margin;

  const addLine = (text, size = 11, bold = false, color = [232, 234, 240]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, W - margin * 2);
    lines.forEach((line) => {
      if (y > 270) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += size * 0.5;
    });
    y += 2;
  };

  const addRect = (fillColor, height = 10) => {
    doc.setFillColor(...fillColor);
    doc.rect(0, y - height, W, height + 4, "F");
    y += 2;
  };

  // ── Header ──
  doc.setFillColor(13, 15, 20);
  doc.rect(0, 0, W, 297, "F");

  doc.setFillColor(30, 33, 48);
  doc.rect(0, 0, W, 50, "F");

  y = 18;
  addLine("AI Mock Interview Report", 22, true, [232, 234, 240]);
  addLine(`Role: ${interview.jobRole}`, 13, false, [144, 151, 176]);
  addLine(`Date: ${new Date(interview.createdAt).toLocaleDateString()}`, 11, false, [93, 100, 128]);
  y += 8;

  // ── Overall score ──
  const score = interview.overallScore;
  const scoreColor = score >= 7 ? [34, 197, 94] : score >= 4 ? [245, 158, 11] : [239, 68, 68];
  addLine(`Overall Score: ${score !== null ? score + " / 10" : "Incomplete"}`, 16, true, scoreColor);
  y += 6;

  // ── Questions ──
  interview.questions.forEach((q, i) => {
    if (y > 250) { doc.addPage(); y = margin; doc.setFillColor(13,15,20); doc.rect(0,0,W,297,"F"); }

    y += 4;
    doc.setFillColor(26, 29, 40);
    doc.roundedRect(margin - 4, y - 6, W - margin * 2 + 8, 8, 2, 2, "F");
    addLine(`Q${i + 1}: ${q.text}`, 12, true, [232, 234, 240]);
    y += 2;

    const qScore = q.score !== null ? q.score : "-";
    const qColor = q.score >= 7 ? [34,197,94] : q.score >= 4 ? [245,158,11] : [239,68,68];
    addLine(`Score: ${qScore}/10`, 11, true, qColor);

    if (q.answer) {
      addLine("Your Answer:", 10, true, [144, 151, 176]);
      addLine(q.answer.slice(0, 300) + (q.answer.length > 300 ? "…" : ""), 10, false, [93, 100, 128]);
    }

    if (q.feedback) {
      addLine("Feedback:", 10, true, [108, 99, 255]);
      addLine(q.feedback, 10, false, [144, 151, 176]);
    }

    if (q.strengths) {
      addLine("Strengths:", 10, true, [34, 197, 94]);
      addLine(q.strengths, 10, false, [144, 151, 176]);
    }

    if (q.improvements) {
      addLine("Improvements:", 10, true, [245, 158, 11]);
      addLine(q.improvements, 10, false, [144, 151, 176]);
    }

    y += 6;
    doc.setDrawColor(42, 45, 58);
    doc.line(margin, y, W - margin, y);
    y += 6;
  });

  // ── Footer ──
  y = 285;
  addLine("Generated by AI Mock Interview Platform • For practice purposes only", 8, false, [93, 100, 128]);

  doc.save(`interview-report-${interview.jobRole.replace(/\s+/g, "-")}.pdf`);
}
